import type { Attributes, ClassKey, Specialty } from '../types/database'

export const ATTRIBUTE_NAMES: Record<keyof Attributes, string> = { strength: 'Força', agility: 'Agilidade', intellect: 'Intelecto', presence: 'Presença', instinct: 'Instinto' }
export const ATTRIBUTE_KEYS = Object.keys(ATTRIBUTE_NAMES) as (keyof Attributes)[]
export const SPECIALTIES = ['Atletismo','Acrobacia','Furtividade','Investigação','Percepção','Sobrevivência','Medicina','Persuasão','Intimidação','História','Arcanismo','Performance','Rastreamento','Alquimia'] as const

export type ClassDefinition = { key: ClassKey; name: string; role: string; primary: keyof Attributes; resource: string; suggested: Attributes; baseVitality: number; baseResource: number; basicAbility: string; initialAbility: string; specialties: readonly Specialty[] }
export const CLASSES: readonly ClassDefinition[] = [
  { key:'warrior', name:'Guerreiro', role:'Proteção e força na linha de frente', primary:'strength', resource:'Vigor', suggested:{strength:3,agility:1,intellect:0,presence:1,instinct:2}, baseVitality:12, baseResource:3, basicAbility:'Golpe firme — ataque direto e confiável.', initialAbility:'Postura guardiã — protege um aliado próximo.', specialties:['Atletismo','Intimidação','Sobrevivência'] },
  { key:'arcanist', name:'Arcanista', role:'Controle e conhecimento mágico', primary:'intellect', resource:'Foco', suggested:{strength:0,agility:1,intellect:3,presence:1,instinct:2}, baseVitality:8, baseResource:5, basicAbility:'Faísca arcana — manifesta energia à distância.', initialAbility:'Círculo de contenção — limita uma ameaça.', specialties:['Arcanismo','Investigação','História'] },
  { key:'shadow_blade', name:'Lâmina Sombria', role:'Mobilidade, precisão e infiltração', primary:'agility', resource:'Ímpeto', suggested:{strength:1,agility:3,intellect:1,presence:0,instinct:2}, baseVitality:9, baseResource:4, basicAbility:'Corte veloz — golpe preciso em movimento.', initialAbility:'Passo pelas sombras — muda de posição sem se expor.', specialties:['Furtividade','Acrobacia','Percepção'] },
  { key:'necromancer', name:'Necromante', role:'Rituais, desgaste e segredos proibidos', primary:'intellect', resource:'Essência', suggested:{strength:0,agility:1,intellect:3,presence:2,instinct:1}, baseVitality:8, baseResource:5, basicAbility:'Toque fúnebre — canaliza energia de decadência.', initialAbility:'Eco dos mortos — consulta um vestígio espiritual.', specialties:['Arcanismo','Medicina','História'] },
  { key:'bard', name:'Bardo', role:'Apoio, influência e versatilidade', primary:'presence', resource:'Inspiração', suggested:{strength:0,agility:1,intellect:1,presence:3,instinct:2}, baseVitality:9, baseResource:4, basicAbility:'Nota cortante — distrai e desestabiliza.', initialAbility:'Refrão inspirador — fortalece a ação de um aliado.', specialties:['Performance','Persuasão','História'] },
  { key:'druid', name:'Druida', role:'Sobrevivência, cura e forças naturais', primary:'instinct', resource:'Seiva', suggested:{strength:1,agility:1,intellect:0,presence:2,instinct:3}, baseVitality:10, baseResource:4, basicAbility:'Espinho vivo — convoca a natureza contra um alvo.', initialAbility:'Forma guardiã — assume um aspecto natural protetor.', specialties:['Sobrevivência','Medicina','Rastreamento'] },
]
export const getClassDefinition = (key: ClassKey) => CLASSES.find(item => item.key === key) ?? CLASSES[0]
