import { useDeferredValue, useState, type ReactNode } from 'react'
import type { IconName } from '../assets/iconRegistry'
import { ClassCompendiumCard, CompendiumCard, CompendiumDetail, CompendiumEmptyState, CompendiumFilters, CompendiumSearch, CompendiumSection, ConditionReference, EnemyReferenceCard, RegionCompendiumCard, RuleCard, SpecialtyReference } from '../components/Compendium'
import { Icon } from '../components/Icon'
import { ATTRIBUTE_NAMES, type ClassDefinition } from '../game-data/classes'
import { COMPENDIUM_SOURCE, ENEMY_ARCHETYPES, attributeName, classIcon, type CompendiumCategory } from '../game-data/compendium'
import type { Attributes } from '../types/database'
import { RegionArtwork } from '../components/RegionArtwork'

type Detail={title:string;icon:IconName;body:ReactNode}|null
const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()
export function CompendiumPage(){const[query,setQuery]=useState(''),[category,setCategory]=useState<CompendiumCategory|'all'>('all'),[attribute,setAttribute]=useState<keyof Attributes|'all'>('all'),[enemyLevel,setEnemyLevel]=useState<number|'all'>('all'),[detail,setDetail]=useState<Detail>(null);const deferred=useDeferredValue(query);const matches=(...parts:(string|number|undefined)[])=>!deferred.trim()||normalize(parts.join(' ')).includes(normalize(deferred));const visible=(key:CompendiumCategory)=>category==='all'||category===key
 const data={classes:COMPENDIUM_SOURCE.classes.filter(item=>(attribute==='all'||item.primary===attribute)&&matches('classes',item.name,item.role,item.resource,item.basicAbility,item.initialAbility,ATTRIBUTE_NAMES[item.primary])),attributes:COMPENDIUM_SOURCE.attributes.filter(item=>(attribute==='all'||item.key===attribute)&&matches('atributos',item.name,item.definition,item.actions,item.mechanics)),specialties:COMPENDIUM_SOURCE.specialties.filter(item=>(attribute==='all'||item.attribute===attribute)&&matches('especialidades',item.name,item.description,attributeName(item.attribute))),conditions:COMPENDIUM_SOURCE.conditions.filter(item=>matches('condições',item.name,'rodadas cena indefinida')),rules:COMPENDIUM_SOURCE.rules.filter(item=>matches('regras',item.name,item.text)),regions:COMPENDIUM_SOURCE.regions.filter(item=>matches('regiões',item.name,...item.aliases)),enemies:COMPENDIUM_SOURCE.enemies.filter(item=>(enemyLevel==='all'||item.level===enemyLevel)&&matches('inimigos',item.level,item.category,item.stats.damage))}
 const openClass=(item:ClassDefinition)=>setDetail({title:item.name,icon:classIcon(item.key),body:<div className="class-detail"><CharacterArtworkForDetail definition={item}/><p>{item.role}</p><dl><div><dt>Atributo principal</dt><dd>{ATTRIBUTE_NAMES[item.primary]}</dd></div><div><dt>Recurso</dt><dd>{item.resource} · base {item.baseResource}</dd></div><div><dt>Vitalidade base</dt><dd>{item.baseVitality}</dd></div><div><dt>Defesa</dt><dd>8 + Agilidade + Instinto</dd></div></dl><h3>Habilidade básica</h3><p>{item.basicAbility}</p><h3>Habilidade inicial</h3><p>{item.initialAbility}</p><small>Referência de nível 1. Progressão futura não implementada.</small></div>})
 return <div className="compendium-page"><header className="compendium-hero"><div><p className="eyebrow">Arquivo mecânico do Relicário</p><h1>Compêndio</h1><p>Classes, regras e referências reais do sistema reunidas para consulta durante a mesa.</p></div><Icon name="compendio" size={84} decorative/></header><div className="compendium-tools"><CompendiumSearch value={query} onChange={setQuery}/><CompendiumFilters category={category} onCategory={setCategory} attribute={attribute} onAttribute={setAttribute} enemyLevel={enemyLevel} onEnemyLevel={setEnemyLevel}/></div><nav className="compendium-index" aria-label="Categorias do Compêndio">{[['classes','Classes'],['attributes','Atributos'],['specialties','Especialidades'],['conditions','Condições'],['rules','Regras'],['regions','Regiões'],['locations','Locais'],['enemies','Inimigos'],['items','Itens']].map(([key,label])=><button key={key} type="button" onClick={()=>setCategory(key as CompendiumCategory)} aria-pressed={category===key}>{label}</button>)}</nav><div className="compendium-catalog">
 {visible('classes')?<CompendiumSection id="classes" title="Classes" count={data.classes.length}><div className="compendium-class-grid">{data.classes.map(item=><ClassCompendiumCard key={item.key} definition={item} onOpen={()=>openClass(item)}/>)}</div></CompendiumSection>:null}
 {visible('attributes')?<CompendiumSection id="attributes" title="Atributos" count={data.attributes.length}><div className="compendium-grid">{data.attributes.map(item=><CompendiumCard key={item.key} icon={item.icon} title={item.name} kicker="Atributo" onOpen={()=>setDetail({title:item.name,icon:item.icon,body:<><p>{item.definition}</p><h3>Ações relacionadas</h3><p>{item.actions}</p><h3>Uso mecânico</h3><p>Testes usam 1d20 + atributo. {item.mechanics}</p></>})}><p>{item.definition}</p><small>{item.mechanics}</small></CompendiumCard>)}</div></CompendiumSection>:null}
 {visible('specialties')?<CompendiumSection id="specialties" title="Especialidades" count={data.specialties.length}><div className="compendium-grid">{data.specialties.map(item=><SpecialtyReference key={item.name} {...item} onOpen={()=>setDetail({title:item.name,icon:'habilidades',body:<><p>{item.description}</p><h3>Atributo relacionado</h3><p>{attributeName(item.attribute)}</p><h3>Efeito mecânico</h3><p>Se estiver treinada e relacionada ao atributo usado, acrescenta +1 ao teste.</p><p>Treinamento e maestria não possuem níveis adicionais implementados.</p></>})}/>)}</div></CompendiumSection>:null}
 {visible('conditions')?<CompendiumSection id="conditions" title="Condições" count={data.conditions.length}><div className="compendium-grid">{data.conditions.map(item=><ConditionReference key={item.name} {...item} onOpen={()=>setDetail({title:item.name,icon:item.icon,body:<><p>Condição reconhecida pela Mesa.</p><h3>Duração possível</h3><p>Rodadas, cena ou indefinida.</p><h3>Efeito e remoção</h3><p>Não documentados no sistema atual. Nenhum efeito automático é aplicado pelo Compêndio.</p></>})}/>)}</div></CompendiumSection>:null}
 {visible('rules')?<CompendiumSection id="rules" title="Regras" count={data.rules.length}><div className="compendium-grid">{data.rules.map(item=><RuleCard key={item.name} {...item} onOpen={()=>setDetail({title:item.name,icon:item.icon,body:<p>{item.text}</p>})}/>)}</div></CompendiumSection>:null}
 {visible('regions')?<CompendiumSection id="regions" title="Regiões" count={data.regions.length}><div className="compendium-region-grid">{data.regions.map(item=><RegionCompendiumCard key={item.key} region={item} onOpen={()=>setDetail({title:item.name,icon:'mapa',body:<><RegionArtworkForDetail region={item.key} name={item.name}/>{item.aliases.length>1?<><h3>Aliases documentados</h3><p>{item.aliases.join(' · ')}</p></>:<p>Nenhuma descrição adicional cadastrada.</p>}</>})}/>)}</div></CompendiumSection>:null}
 {visible('locations')?<CompendiumSection id="locations" title="Locais" count={0}><CompendiumEmptyState title="Locais" icons={['metropole','cidade','vila','fortaleza','castelo','acampamento','mosteiro','observatorio','ruinas','caverna','mina','porto','ponte-passagem','estrada']}/></CompendiumSection>:null}
 {visible('enemies')?<CompendiumSection id="enemies" title="Inimigos" count={data.enemies.length}><p className="compendium-note">Templates mecânicos para a Mesa, não criaturas narrativas prontas. Arquétipos disponíveis: {ENEMY_ARCHETYPES.join(', ')}.</p><div className="compendium-grid">{data.enemies.map(item=><EnemyReferenceCard key={`${item.level}-${item.category}`} {...item} onOpen={()=>setDetail({title:`Nível ${item.level} · ${item.category}`,icon:item.category==='chefe'?'chefe':'monstro',body:<><p>Referência mecânica aplicável a qualquer arquétipo existente.</p><dl className="detail-stats"><div><dt>Vitalidade</dt><dd>{item.stats.vitalityMax}</dd></div><div><dt>Defesa</dt><dd>{item.stats.defense}</dd></div><div><dt>Ataque</dt><dd>+{item.stats.attackBonus}</dd></div><div><dt>Dano</dt><dd>{item.stats.damage}</dd></div><div><dt>Dificuldade de efeito</dt><dd>{item.stats.effectDifficulty}</dd></div></dl></>})}/>)}</div></CompendiumSection>:null}
 {visible('items')?<CompendiumSection id="items" title="Itens" count={0}><CompendiumEmptyState title="Itens e equipamentos" icons={['inventario','equipamento','capacete','armadura','luvas','botas','anel','amuleto','ouro']}/></CompendiumSection>:null}
 </div>{detail?<CompendiumDetail title={detail.title} icon={detail.icon} onClose={()=>setDetail(null)}>{detail.body}</CompendiumDetail>:null}</div>}
function CharacterArtworkForDetail({definition}:{definition:ClassDefinition}){return <div className="detail-art"><Icon name={classIcon(definition.key)} size={30} decorative/><span>{definition.name}</span></div>}
function RegionArtworkForDetail({region,name}:{region:string;name:string}){return <RegionArtwork region={region} alt={name} className="detail-region" loading="lazy"/>}
