import { useMemo, useState } from 'react'
import { Navigate, useNavigate } from 'react-router-dom'
import { AvatarPreview } from '../components/AvatarPreview'
import { ErrorBanner, LoadingState, PageHeader } from '../components/States'
import { createMyCharacter, type CreateCharacterInput } from '../data/campaigns'
import { ATTRIBUTE_KEYS, ATTRIBUTE_NAMES, CLASSES, getClassDefinition, SPECIALTIES } from '../game-data/classes'
import { calculateDerived, isValidAttributeDistribution, isValidSpecialties } from '../game-data/rules'
import { useCampaign } from '../hooks/useCampaign'
import { useAuth } from '../auth/AuthContext'
import type { Attributes, AvatarOptions, ClassKey, Specialty } from '../types/database'

const STEPS=['Classe','Atributos','Identidade','Vínculo','Especialidades','Visual','Revisão']
const BONDS=['Amigos','Irmãos','Casal','Desconhecidos','Antigos rivais','Membros da mesma ordem','Dívida compartilhada','Um salvou o outro','Personalizado']
const defaultAvatar:AvatarOptions={presentation:'andrógena',skinTone:'#b97850',hair:'#34251e',primaryColor:'#7f3f36',secondaryColor:'#4f624c',accessory:'broche'}
export function CreateCharacterPage(){const {session}=useAuth();const {data,loading}=useCampaign(session?.user.id);const navigate=useNavigate();const [step,setStep]=useState(0);const [classKey,setClassKey]=useState<ClassKey>('warrior');const role=getClassDefinition(classKey);const [attributes,setAttributes]=useState<Attributes>(role.suggested);const [form,setForm]=useState({name:'',presentation:'',origin:'',appearance:'',personality:'',objective:'',fear:'',bond:'Amigos',customBond:''});const [specialties,setSpecialties]=useState<Specialty[]>([]);const [avatar,setAvatar]=useState(defaultAvatar);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const derived=useMemo(()=>calculateDerived(classKey,attributes),[classKey,attributes]);
  if(loading)return <LoadingState/>;if(data?.characters.some(c=>c.owner_id===session?.user.id))return <Navigate to="/personagem" replace/>;if(!data)return <><PageHeader eyebrow="Criação" title="Campanha necessária"/><ErrorBanner>Seu usuário precisa estar vinculado a uma campanha antes de criar a ficha.</ErrorBanner></>;
  const bond=form.bond==='Personalizado'?form.customBond.trim():form.bond;const valid=[true,isValidAttributeDistribution(attributes),Boolean(form.name.trim()&&form.presentation.trim()&&form.origin.trim()&&form.appearance.trim()&&form.personality.trim()&&form.objective.trim()&&form.fear.trim()),Boolean(bond),isValidSpecialties(specialties,role.specialties),true,true][step];
  function chooseClass(key:ClassKey){setClassKey(key);setAttributes(getClassDefinition(key).suggested);setSpecialties([])} function setField(name:keyof typeof form,value:string){setForm(current=>({...current,[name]:value}))}
  async function confirm(){if(!session||!isValidAttributeDistribution(attributes)||!isValidSpecialties(specialties,role.specialties))return;setSaving(true);setError('');const payload:CreateCharacterInput={name:form.name.trim(),class_key:classKey,presentation:form.presentation.trim(),origin:form.origin.trim(),appearance:form.appearance.trim(),personality:form.personality.trim(),objective:form.objective.trim(),fear:form.fear.trim(),bond,attributes,specialties,avatar};try{await createMyCharacter(payload);navigate('/personagem',{replace:true})}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível criar a ficha.')}finally{setSaving(false)}}
  return <div className="creation-page"><PageHeader eyebrow={`Marco 3 · etapa ${step+1} de ${STEPS.length}`} title="Forje sua ficha">As escolhas mecânicas ficam visíveis antes da confirmação. Depois, classe e atributos só mudam por uma ação explícita.</PageHeader><ol className="stepper" aria-label="Etapas da criação">{STEPS.map((label,index)=><li key={label} className={index===step?'active':index<step?'done':''}><button onClick={()=>index<step&&setStep(index)} disabled={index>step}><span>{index+1}</span>{label}</button></li>)}</ol><section className="creation-stage" aria-labelledby="stage-title">{step===0?<ClassStep selected={classKey} choose={chooseClass}/>:null}{step===1?<AttributesStep value={attributes} onChange={setAttributes} derived={derived}/>:null}{step===2?<IdentityStep form={form} setField={setField}/>:null}{step===3?<BondStep form={form} setField={setField}/>:null}{step===4?<SpecialtiesStep selected={specialties} suggestions={role.specialties} onChange={setSpecialties}/>:null}{step===5?<VisualStep avatar={avatar} setAvatar={setAvatar} name={form.name}/>:null}{step===6?<Review input={{...form,bond,classKey,attributes,specialties,avatar}} derived={derived}/>:null}</section>{error?<ErrorBanner>{error}</ErrorBanner>:null}<div className="wizard-actions">{step>0?<button onClick={()=>setStep(value=>value-1)}>Voltar</button>:<span/>}{step<STEPS.length-1?<button className="primary-button" disabled={!valid} onClick={()=>setStep(value=>value+1)}>Continuar</button>:<button className="primary-button" disabled={saving} onClick={()=>void confirm()}>{saving?'Criando ficha…':'Criar meu personagem'}</button>}</div></div>}

function ClassStep({selected,choose}:{selected:ClassKey;choose:(key:ClassKey)=>void}){return <><h2 id="stage-title">Escolha sua classe</h2><div className="class-grid">{CLASSES.map(item=><button className={item.key===selected?'class-option selected':'class-option'} onClick={()=>choose(item.key)} key={item.key} aria-pressed={item.key===selected}><span>{item.role}</span><strong>{item.name}</strong><dl><div><dt>Atributo</dt><dd>{ATTRIBUTE_NAMES[item.primary]}</dd></div><div><dt>Recurso</dt><dd>{item.resource}</dd></div></dl><p>{item.basicAbility}</p><p>{item.initialAbility}</p></button>)}</div></>}
function AttributesStep({value,onChange,derived}:{value:Attributes;onChange:(v:Attributes)=>void;derived:ReturnType<typeof calculateDerived>}){return <><h2 id="stage-title">Distribua seus atributos</h2><p className="stage-help">Use cada valor uma vez: 3, 2, 1, 1 e 0. A soma permanece 7.</p><div className="attribute-grid">{ATTRIBUTE_KEYS.map(key=><label key={key}>{ATTRIBUTE_NAMES[key]}<select value={value[key]} onChange={e=>onChange({...value,[key]:Number(e.target.value)})}>{[0,1,2,3].map(n=><option key={n}>{n}</option>)}</select></label>)}</div>{!isValidAttributeDistribution(value)?<ErrorBanner>A distribuição deve conter exatamente 3, 2, 1, 1 e 0.</ErrorBanner>:null}<Derived derived={derived}/></>}
function IdentityStep({form,setField}:{form:Record<string,string>;setField:(name:'name'|'presentation'|'origin'|'appearance'|'personality'|'objective'|'fear',value:string)=>void}){const fields=[['name','Nome',80],['presentation','Gênero ou apresentação',80],['origin','Origem',120],['appearance','Aparência',800],['personality','Personalidade',800],['objective','Objetivo',500],['fear','Medo',500]] as const;return <><h2 id="stage-title">Dê identidade ao personagem</h2><div className="form-grid">{fields.map(([key,label,max])=><label key={key} className={key==='name'||key==='presentation'||key==='origin'?'':'wide'}>{label}{max>120?<textarea required maxLength={max} value={form[key]} onChange={e=>setField(key,e.target.value)}/>:<input required maxLength={max} value={form[key]} onChange={e=>setField(key,e.target.value)}/>}</label>)}</div></>}
function BondStep({form,setField}:{form:Record<string,string>;setField:(name:'bond'|'customBond',value:string)=>void}){return <><h2 id="stage-title">Como vocês começam ligados?</h2><p className="stage-help">O vínculo inicial fica preservado. O vínculo atual começa igual e poderá evoluir na ficha.</p><div className="bond-grid">{BONDS.map(item=><label key={item}><input type="radio" name="bond" checked={form.bond===item} onChange={()=>setField('bond',item)}/>{item}</label>)}</div>{form.bond==='Personalizado'?<label>Descreva o vínculo<input maxLength={240} value={form.customBond} onChange={e=>setField('customBond',e.target.value)}/></label>:null}</>}
function SpecialtiesStep({selected,suggestions,onChange}:{selected:Specialty[];suggestions:readonly Specialty[];onChange:(v:Specialty[])=>void}){function toggle(value:Specialty){onChange(selected.includes(value)?selected.filter(item=>item!==value):selected.length<3?[...selected,value]:selected)}return <><h2 id="stage-title">Escolha três especialidades</h2><p className="stage-help">Duas devem vir das sugestões da classe; a terceira pode ser qualquer especialidade.</p><div className="specialty-grid">{SPECIALTIES.map(item=><label className={suggestions.includes(item)?'suggested':''} key={item}><input type="checkbox" checked={selected.includes(item)} onChange={()=>toggle(item)}/>{item}{suggestions.includes(item)?<small>Sugestão</small>:null}</label>)}</div><p>{selected.length}/3 escolhidas</p>{selected.length===3&&!isValidSpecialties(selected,suggestions)?<ErrorBanner>Escolha pelo menos duas sugestões da classe.</ErrorBanner>:null}</>}
function VisualStep({avatar,setAvatar,name}:{avatar:AvatarOptions;setAvatar:(v:AvatarOptions)=>void;name:string}){const set=(key:keyof AvatarOptions,value:string)=>setAvatar({...avatar,[key]:value});return <><h2 id="stage-title">Monte uma silhueta inicial</h2><div className="visual-builder"><AvatarPreview avatar={avatar} name={name}/><div className="visual-controls"><label>Apresentação do avatar<select value={avatar.presentation} onChange={e=>set('presentation',e.target.value)}><option>feminina</option><option>masculina</option><option>andrógena</option></select></label><Color label="Tom de pele" value={avatar.skinTone} change={v=>set('skinTone',v)}/><Color label="Cabelo" value={avatar.hair} change={v=>set('hair',v)}/><Color label="Roupa principal" value={avatar.primaryColor} change={v=>set('primaryColor',v)}/><Color label="Roupa secundária" value={avatar.secondaryColor} change={v=>set('secondaryColor',v)}/><label>Acessório<select value={avatar.accessory} onChange={e=>set('accessory',e.target.value)}><option value="broche">Broche</option><option value="capa">Capa</option><option value="brinco">Brinco</option><option value="nenhum">Nenhum</option></select></label></div></div></>}
function Color({label,value,change}:{label:string;value:string;change:(v:string)=>void}){return <label>{label}<input type="color" value={value} onChange={e=>change(e.target.value)}/></label>}
function Derived({derived}:{derived:ReturnType<typeof calculateDerived>}){return <dl className="derived-strip"><div><dt>Vitalidade</dt><dd>{derived.vitality}</dd></div><div><dt>Defesa</dt><dd>{derived.defense}</dd></div><div><dt>Inventário</dt><dd>{derived.inventoryCapacity}</dd></div><div><dt>Recurso</dt><dd>{derived.resource}</dd></div></dl>}
function Review({input,derived}:{input:{name:string;presentation:string;origin:string;appearance:string;personality:string;objective:string;fear:string;bond:string;classKey:ClassKey;attributes:Attributes;specialties:Specialty[];avatar:AvatarOptions};derived:ReturnType<typeof calculateDerived>}){const role=getClassDefinition(input.classKey);return <><h2 id="stage-title">Revise antes de criar</h2><div className="review-layout"><AvatarPreview avatar={input.avatar} name={input.name}/><div><p className="eyebrow">{role.name} · nível 1</p><h3>{input.name}</h3><p>{input.presentation} · {input.origin}</p><Derived derived={derived}/><dl className="review-list"><div><dt>Atributos</dt><dd>{ATTRIBUTE_KEYS.map(k=>`${ATTRIBUTE_NAMES[k]} ${input.attributes[k]}`).join(' · ')}</dd></div><div><dt>Especialidades</dt><dd>{input.specialties.join(', ')}</dd></div><div><dt>Habilidade básica</dt><dd>{role.basicAbility}</dd></div><div><dt>Habilidade inicial</dt><dd>{role.initialAbility}</dd></div><div><dt>Vínculo inicial e atual</dt><dd>{input.bond}</dd></div><div><dt>Aparência</dt><dd>{input.appearance}</dd></div><div><dt>Personalidade</dt><dd>{input.personality}</dd></div><div><dt>Objetivo / medo</dt><dd>{input.objective} / {input.fear}</dd></div></dl></div></div></>}
