// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest'
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { aurenNonInteractiveLayerIds, aurenRegions, mapRegistry } from '../assets/mapRegistry'
import { resolveRegionKey } from '../assets/regionRegistry'
import { AurenMap } from '../components/AurenMap'
import { RegionArtwork } from '../components/RegionArtwork'
import { isAurenActivationKey, prepareAurenSvg, visibleMapLocations, type MapLocation } from '../components/aurenMapUtils'

const svg=`<svg id="mapa-auren" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1591.7 916.3"><g id="vale-de-ardan"><path d="M0 0h20v20z"/></g><g id="arquipelago-de-vesper"><path d="M30 0h20v20z"/></g><g id="divisoes-internas"/><path id="contorno-geral" d="M0 0h20v20z"/></svg>`
afterEach(()=>{cleanup();vi.restoreAllMocks()})

describe('mapa de Auren',()=>{
  it('carrega arte, interação e água no mesmo plano lógico',()=>{expect(existsSync(resolve('public/assets/maps/mapa-realista-cortado.png'))).toBe(true);expect(existsSync(resolve('public/assets/maps/mapa-auren.svg'))).toBe(true);expect(existsSync(resolve('public/assets/maps/agua.jpg'))).toBe(true);expect(mapRegistry.auren.viewBox).toBe('0 0 1591.7 916.3');expect(mapRegistry.auren.width/mapRegistry.auren.height).toBeCloseTo(1591.7/916.3,8);expect(Math.abs(mapRegistry.auren.rasterWidth/mapRegistry.auren.rasterHeight-mapRegistry.auren.width/mapRegistry.auren.height)).toBeLessThan(.002)})
  it('mapeia IDs oficiais e aliases sem alterar nomes narrativos',()=>{expect(aurenRegions['pantanos-de-varg'].regionKey).toBe('pantanos-negros');expect(aurenRegions['floresta-de-nhalor'].regionKey).toBe('floresta-antiga');expect(aurenRegions['arquipelago-de-vesper'].regionKey).toBe('arquipelago-de-vesper');expect(aurenRegions.ormara.regionKey).toBe('ormara');expect(resolveRegionKey('Deserto de Sal')).toBe('deserto-branco');expect(resolveRegionKey('Península da Aurora')).toBe('peninsula-dos-mosteiros')})
  it('reconhece todos os IDs reais do SVG e oculta camadas passivas',()=>{const source=readFileSync(resolve('public/assets/maps/mapa-auren.svg'),'utf8');const markup=prepareAurenSvg(source);const doc=new DOMParser().parseFromString(markup,'image/svg+xml');for(const id of Object.keys(aurenRegions))expect(doc.getElementById(id)?.getAttribute('role')).toBe('button');for(const id of aurenNonInteractiveLayerIds){expect(doc.getElementById(id)?.getAttribute('data-non-interactive')).toBe('true');expect(doc.getElementById(id)?.getAttribute('display')).toBe('none')}expect(doc.documentElement.getAttribute('preserveAspectRatio')).toBe('none')})
  it('seleciona por clique e reconhece Enter e Espaço',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,text:async()=>svg}));const select=vi.fn();const {container}=render(<AurenMap selected={null} onSelect={select}/>);await screen.findAllByRole('button',{name:'Vale de Ardan'});const region=container.querySelector<SVGElement>('[data-auren-region="vale-de-ardan"]')!;fireEvent.click(region);expect(select).toHaveBeenCalledWith('vale-de-ardan');expect(isAurenActivationKey('Enter')).toBe(true);expect(isAurenActivationKey(' ')).toBe(true);expect(isAurenActivationKey('Escape')).toBe(false)})
  it('mantém água repetida e suavizada, arte e SVG no mesmo plano transformável',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,text:async()=>svg}));const {container}=render(<AurenMap selected={null} onSelect={()=>{}}/>);await screen.findAllByRole('button',{name:'Vale de Ardan'});const viewport=screen.getByTestId('map-viewport');const stage=screen.getByTestId('map-stage');const water=container.querySelector<HTMLElement>('[data-map-layer="water"]');const artwork=container.querySelector('[data-map-layer="artwork"]');const interactive=container.querySelector('[data-map-layer="interactive"]');expect(viewport).toHaveAttribute('data-water-pattern','repeat');expect(water?.style.backgroundImage).toContain(mapRegistry.auren.water);expect(water?.parentElement).toBe(stage);expect(artwork?.parentElement).toBe(stage);expect(interactive?.parentElement).toBe(stage);const css=readFileSync(resolve('src/components/AurenMap.css'),'utf8');expect(css).toContain('background-repeat: repeat');expect(css).toContain('background-size: 312px 312px');expect(css).toContain('opacity: .38');expect(css).toContain('background-color: #102936');expect(css).toContain('radial-gradient');expect(css).toContain('stroke: transparent !important');expect(css).toContain('scrollbar-width: none')})
  it('mantém estado vazio e oculta locais não revelados',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,text:async()=>svg}));const hidden:MapLocation={id:'x',name:'Oculto',kind:'cidade',x:.5,y:.5,revealed:false,regionId:'vale-de-ardan'};render(<AurenMap selected={null} onSelect={()=>{}} locations={[hidden]}/>);expect(await screen.findByText('Nenhum local revelado disponível para exibição.')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Oculto'})).not.toBeInTheDocument();expect(visibleMapLocations([hidden])).toHaveLength(0);expect(screen.getByTestId('map-viewport')).toHaveClass('auren-map__viewport')})
  it('mostra fallback quando SVG ou imagem falham',async()=>{vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new Error('falha')));const {container}=render(<AurenMap selected={null} onSelect={()=>{}}/>);expect(await screen.findByRole('alert')).toHaveTextContent('camada interativa');fireEvent.error(container.querySelector('img')!);await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('imagem ilustrada'))})
  it('usa fallback acessível quando a imagem regional falha',()=>{const {container}=render(<RegionArtwork region="ormara" alt="Ormara"/>);fireEvent.error(container.querySelector('img')!);expect(screen.getByRole('img',{name:'Ormara'})).toHaveClass('region-artwork--fallback')})
})
