import { useCallback, useEffect, useMemo, useState } from 'react'
import { useAuth } from '../auth/AuthContext'
import { addCondition, removeCondition, updateCharacterState } from '../data/campaigns'
import { combatRepository, CombatSchemaMissingError, type CombatParticipant, type CombatSnapshot, type EnemyInstance } from '../data/combat'
import { applyDamage, applyHealing, canUseTableControls } from '../game-data/rules'
import { clampResource, reorderInitiative, resolveEnemyAttack, tickConditions, type ConditionDuration } from '../game-data/table'
import { useCampaign } from '../hooks/useCampaign'
import { supabase } from '../lib/supabase'
import type { Character } from '../types/database'
import { ErrorBanner, LoadingState, PageHeader } from '../components/States'
import { Icon } from '../components/Icon'
import { ActionToast, CombatControls, CombatEmptyState, DiceRoller, EnemyAttackPanel, EnemyCard, EnemyCreator, InitiativeTracker, PlayerCombatCard, QuickRoll, type Enemy, type TableCondition } from '../components/table/TableTools'

type Section='players'|'dice'|'combat'|'enemies'
const EMPTY_COMBAT:CombatSnapshot={session:null,participants:[],enemies:[],actions:[]}
function uiEnemy(enemy:EnemyInstance,participants:CombatParticipant[]):Enemy{return{id:enemy.id,name:enemy.name,level:enemy.level,category:enemy.category,archetype:enemy.archetype,vitality:enemy.vitality,vitalityMax:enemy.vitality_max,defense:enemy.defense,attackBonus:enemy.attack_bonus,damage:enemy.damage_expression,effectDifficulty:enemy.effect_difficulty,zone:enemy.zone,status:enemy.status,initiative:participants.find(item=>item.enemy_instance_id===enemy.id)?.initiative??0,conditions:enemy.conditions}}

export function TablePage(){
  const{session}=useAuth();const{data,loading,error,refresh}=useCampaign(session?.user.id);const[section,setSection]=useState<Section>('players'),[message,setMessage]=useState<string|null>(null),[actionError,setActionError]=useState<string|null>(null),[combat,setCombat]=useState<CombatSnapshot>(EMPTY_COMBAT),[schemaMissing,setSchemaMissing]=useState(false)
  const isAdmin=canUseTableControls(data?.currentRole??null),campaignId=data?.campaign.id,userId=session?.user.id
  const loadCombat=useCallback(async()=>{if(!campaignId)return;try{setCombat(await combatRepository.load(campaignId));setSchemaMissing(false)}catch(cause){if(cause instanceof CombatSchemaMissingError){setSchemaMissing(true);setCombat(EMPTY_COMBAT)}else setActionError('Não foi possível atualizar o combate compartilhado.')}},[campaignId])
  useEffect(()=>{void loadCombat()},[loadCombat])
  useEffect(()=>{if(!campaignId||schemaMissing)return;const channel=combatRepository.subscribe(campaignId,()=>void loadCombat());return()=>{void supabase.removeChannel(channel)}},[campaignId,loadCombat,schemaMissing])
  const orderedParticipants=useMemo(()=>[...combat.participants].sort((a,b)=>a.position-b.position),[combat.participants])
  const enemies=useMemo(()=>combat.enemies.map(enemy=>uiEnemy(enemy,combat.participants)),[combat.enemies,combat.participants])
  if(loading)return <LoadingState/>
  function note(text:string){setMessage(text);window.setTimeout(()=>setMessage(null),2600)}
  async function run(action:()=>Promise<unknown>,success:string,refreshCharacters=false){try{setActionError(null);await action();if(refreshCharacters)await refresh();await loadCombat();note(success)}catch(cause){setActionError(cause instanceof Error?cause.message:'A alteração não foi salva. Verifique sua permissão e tente novamente.')}}
  function confirmLoss(text:string){return window.confirm(text)}
  async function alter(character:Character,kind:'damage'|'heal'|'resource',amount:number){const state=character.character_states;if(!state||!userId)return;let vitality=state.vitality_current,resource=state.resource_current;if(kind==='damage'){if(!confirmLoss(`Aplicar ${amount} de dano a ${character.name}?`))return;vitality=applyDamage(state,amount).vitality_current}else if(kind==='heal')vitality=applyHealing(state,amount).vitality_current;else{if(amount<0&&!confirmLoss(`Gastar ${Math.abs(amount)} de recurso de ${character.name}?`))return;resource=clampResource(state.resource_current,amount,state.resource_max)}const before={vitality_current:state.vitality_current,resource_current:state.resource_current},after={vitality_current:vitality,resource_current:resource},verb=kind==='damage'?`sofreu ${amount} de dano`:kind==='heal'?`recuperou ${amount} de Vitalidade`:`teve o recurso ajustado em ${amount}`;await run(()=>combat.session?combatRepository.updateWithAction(combat.session,userId,'character_states',character.id,before,after,kind,`${character.name} ${verb}.`):updateCharacterState(character.id,after,userId),`${character.name} ${verb}.`,true)}
  async function updateParticipant(participant:CombatParticipant,after:Record<string,unknown>,type:string,summary:string){if(!combat.session||!userId)return;const before=Object.fromEntries(Object.keys(after).map(key=>[key,participant[key as keyof CombatParticipant]]));await run(()=>combatRepository.updateWithAction(combat.session!,userId,'combat_participants',participant.id,before,after,type,summary),summary)}
  function characterParticipant(characterId:string){return combat.participants.find(item=>item.character_id===characterId)}
  async function addTimedCondition(character:Character,name:TableCondition,duration:ConditionDuration){if(!userId)return;const participant=characterParticipant(character.id);await run(async()=>{await addCondition(character.id,name,userId);if(participant&&combat.session)await combatRepository.updateWithAction(combat.session,userId,'combat_participants',participant.id,{conditions:participant.conditions},{conditions:[...participant.conditions,{name,duration}]},'condition_added',`${character.name} recebeu ${name}.`)},`${character.name} recebeu ${name}.`,true)}
  async function attack(enemy:Enemy,target:Character){if(!combat.session||!userId||!target.character_states)return;const result=resolveEnemyAttack(enemy.attackBonus,target.defense,enemy.damage);const attackText=`${enemy.name} rolou ${result.attack.total} contra Defesa ${target.defense}.`;if(!result.hit){await run(()=>combatRepository.action(combat.session!.campaign_id,combat.session!.id,userId,{action_type:'enemy_attack_miss',summary:`${attackText} Errou.`,target_table:null,target_id:null,before_state:null,after_state:null,reversible:false}),`${attackText} Errou.`);return}const damage=result.damage!.total;if(!confirmLoss(`${attackText} Acertou. Aplicar ${damage} de dano a ${target.name}?`))return;const state=target.character_states,after={vitality_current:applyDamage(state,damage).vitality_current,resource_current:state.resource_current};await run(()=>combatRepository.updateWithAction(combat.session!,userId,'character_states',target.id,{vitality_current:state.vitality_current,resource_current:state.resource_current},after,'enemy_attack',`${attackText} Acertou e causou ${damage} de dano em ${target.name}.`),`${enemy.name} causou ${damage} de dano em ${target.name}.`,true)}
  const tabs:[Section,string][]=[['players','Jogadores'],['dice','Dados'],['combat','Combate'],['enemies','Inimigos']]
  return <main className="table-page"><PageHeader eyebrow="Mesa compartilhada" title="Controle mecânico">Estado, rolagens e combate leve para dois jogadores. A condução da história permanece com o GPT Mestre.</PageHeader>{error||actionError?<ErrorBanner>{error??actionError}</ErrorBanner>:null}{schemaMissing?<ErrorBanner>A Mesa compartilhada ainda não está instalada. Aplique a migração 202607130001_combat_relicary.sql; fichas e controles de personagem continuam disponíveis.</ErrorBanner>:null}<nav className="table-tabs" aria-label="Seções da Mesa">{tabs.map(([key,label])=><button key={key} aria-selected={section===key} onClick={()=>setSection(key)}>{label}</button>)}</nav><div className="table-layout">
    <section className={`table-panel table-panel--players ${section==='players'?'is-visible':''}`} aria-label="Jogadores"><div className="table-section-heading"><div><h2>Jogadores</h2><p>Os dois protagonistas e seu estado sincronizado.</p></div></div>{data?.characters.length?<div className="table-players">{data.characters.map((character,index)=>{const participant=characterParticipant(character.id);return <PlayerCombatCard key={character.id} character={character} playerName={data.members[index]?.user_id===session?.user.id?'Você':undefined} isAdmin={isAdmin} combatConditions={participant?.conditions} fallen={participant?.fallen} stable={participant?.stable} onDamage={n=>void alter(character,'damage',n)} onHeal={n=>void alter(character,'heal',n)} onResource={n=>void alter(character,'resource',n)} onAddCondition={(name,duration)=>void addTimedCondition(character,name,duration)} onRemoveCondition={(id,name)=>{if(confirmLoss(`Remover ${name} de ${character.name}?`))void run(()=>removeCondition(id),`${name} removido de ${character.name}.`,true)}} onFallen={()=>participant&&void updateParticipant(participant,{fallen:true,stable:false},'character_fallen',`${character.name} ficou Caído.`)} onStabilize={()=>participant&&void updateParticipant(participant,{stable:true},'character_stable',`${character.name} foi estabilizado.`)}/>})}</div>:<div className="table-players-empty"><Icon name="personagens" size={40} decorative/><h3>Nenhum personagem criado ainda</h3><p>Assim que um dos assentos criar a ficha, o estado mecânico aparece aqui.</p></div>}</section>
    <aside className={`table-panel table-panel--dice ${section==='dice'?'is-visible':''}`}><DiceRoller onRoll={r=>note(`Rolagem livre: ${r.quantity}d${r.sides} ${r.modifier>=0?'+':'-'} ${Math.abs(r.modifier)} = ${r.total}.`)}/><QuickRoll characters={data?.characters??[]} onRoll={r=>note(`Teste de atributo: 1d20 + ${r.modifier} = ${r.total}.`)}/></aside>
    <section className={`table-panel table-panel--combat ${section==='combat'?'is-visible':''}`}>{combat.session?<><div className="table-section-heading"><div><h2>Combate tático leve</h2><p>Zonas, iniciativa, rodadas e turnos.</p></div>{isAdmin?<button onClick={()=>userId&&void run(()=>combatRepository.undoLast(combat,userId),'A última alteração foi desfeita.',true)}>Desfazer última alteração</button>:null}</div><CombatControls round={combat.session.round} turn={combat.session.turn_index} count={orderedParticipants.length} onAdvance={next=>{if(!userId)return;const previousRound=combat.session!.round;void run(async()=>{await combatRepository.updateWithAction(combat.session!,userId,'combat_sessions',combat.session!.id,{round:previousRound,turn_index:combat.session!.turn_index},{round:next.round,turn_index:next.turn},'turn_advanced',`Combate avançou para a rodada ${next.round}, turno ${next.turn+1}.`);if(next.round>previousRound)await Promise.all(orderedParticipants.map(participant=>combatRepository.updateWithAction(combat.session!,userId,'combat_participants',participant.id,{conditions:participant.conditions},{conditions:tickConditions(participant.conditions)},'conditions_ticked',`Durações de ${participant.display_name} avançaram.`)))},`Combate avançou para a rodada ${next.round}, turno ${next.turn+1}.`)}} onEnd={()=>{if(userId&&confirmLoss('Encerrar o combate atual?'))void run(()=>combatRepository.end(combat.session!,userId),'Combate encerrado.')}}/><InitiativeTracker participants={orderedParticipants.map(item=>({id:item.id,name:item.display_name,initiative:item.initiative}))} turn={combat.session.turn_index} isAdmin={isAdmin} onTurn={turn=>userId&&void run(()=>combatRepository.updateWithAction(combat.session!,userId,'combat_sessions',combat.session!.id,{turn_index:combat.session!.turn_index},{turn_index:turn},'turn_selected',`Turno definido para ${turn+1}.`),`Turno definido para ${turn+1}.`)} onInitiative={(id,value)=>{const participant=combat.participants.find(item=>item.id===id);if(participant)void updateParticipant(participant,{initiative:value},'initiative_changed',`Iniciativa de ${participant.display_name} alterada para ${value}.`)}} onReorder={(from,to)=>userId&&void run(()=>combatRepository.reorder(combat.session!,userId,reorderInitiative(orderedParticipants,from,to)),'Ordem de iniciativa ajustada.')}/></>:<CombatEmptyState disabled={!isAdmin||schemaMissing} onStart={()=>{if(!campaignId||!userId)return;void run(()=>combatRepository.start(campaignId,userId,(data?.characters??[]).map(character=>({id:character.id,name:character.name,initiative:character.attributes.agility}))),'Combate iniciado.')}}/>}</section>
    <section className={`table-panel table-panel--enemies ${section==='enemies'?'is-visible':''}`}>{combat.session&&isAdmin?<EnemyCreator onCreate={enemy=>userId&&void run(()=>combatRepository.addEnemy(combat.session!,userId,{name:enemy.name,level:enemy.level,category:enemy.category,archetype:enemy.archetype,vitality:enemy.vitality,vitality_max:enemy.vitalityMax,defense:enemy.defense,attack_bonus:enemy.attackBonus,damage_expression:enemy.damage,effect_difficulty:enemy.effectDifficulty,zone:enemy.zone,status:enemy.status,conditions:[]} ),`${enemy.name} entrou no combate.`)}/>:null}<div className="enemy-list">{enemies.map(enemy=><EnemyCard key={enemy.id} enemy={enemy} isAdmin={isAdmin} onChange={next=>{const stored=combat.enemies.find(item=>item.id===next.id);if(stored&&userId)void run(()=>combatRepository.updateWithAction(combat.session!,userId,'enemy_instances',stored.id,{vitality:stored.vitality,status:stored.status,zone:stored.zone},{vitality:next.vitality,status:next.status,zone:next.zone},'enemy_changed',`${next.name} foi atualizado.`),`${next.name} foi atualizado.`)}}/>)}</div>{combat.session?<EnemyAttackPanel enemies={enemies} characters={data?.characters??[]} disabled={!isAdmin} onAttack={(enemy,target)=>void attack(enemy,target)}/>:<p>Inicie um combate para controlar inimigos temporários.</p>}</section>
  </div>{combat.actions.length?<section className="mechanical-history"><h2>Alterações recentes</h2><ol>{combat.actions.map(item=><li key={item.id}>{item.undone_at?'Desfeito · ':''}{item.summary}</li>)}</ol></section>:null}{data&&!isAdmin?<p className="permission-note">Você pode acompanhar toda a Mesa. Controles compartilhados permanecem reservados ao administrador pelas políticas atuais.</p>:null}<ActionToast message={message}/></main>
}
