import { useState } from 'react'
import { useAuth } from '../auth/AuthContext'
import { addCondition, removeCondition, updateCharacterState } from '../data/campaigns'
import { applyDamage, applyHealing, canUseTableControls } from '../game-data/rules'
import { useCampaign } from '../hooks/useCampaign'
import type { Character } from '../types/database'
import { EmptyState, ErrorBanner, LoadingState, PageHeader } from '../components/States'

export function TablePage(){const {session}=useAuth();const {data,loading,error,refresh}=useCampaign(session?.user.id);const [actionError,setActionError]=useState<string|null>(null);if(loading)return <LoadingState/>;const isAdmin=canUseTableControls(data?.currentRole??null);async function run(action:()=>Promise<void>){try{setActionError(null);await action();await refresh()}catch{setActionError('A alteração não foi salva. Verifique sua permissão e tente novamente.')}}return <><PageHeader eyebrow="Controle de mesa" title="Estado em paralelo">Dano, cura e condições são alterações mecânicas. A condução da história continua com o GPT Mestre.</PageHeader>{error||actionError?<ErrorBanner>{error??actionError}</ErrorBanner>:null}{!data?.characters.length?<EmptyState title="A mesa está vazia">Crie os personagens no Supabase para habilitar os controles.</EmptyState>:<section className="table-grid">{data.characters.map(character=><TableCharacter key={character.id} character={character} isAdmin={isAdmin} userId={session!.user.id} run={run}/>)}</section>}{data&&!isAdmin?<p className="permission-note">Somente o administrador da mesa pode usar os controles compartilhados.</p>:null}</>}
function TableCharacter({character,isAdmin,userId,run}:{character:Character;isAdmin:boolean;userId:string;run:(action:()=>Promise<void>)=>Promise<void>}){const [amount,setAmount]=useState(1);const [condition,setCondition]=useState('');const state=character.character_states;async function alter(kind:'damage'|'heal'){if(!state)return;const next=kind==='damage'?applyDamage(state,amount):applyHealing(state,amount);await run(()=>updateCharacterState(character.id,{vitality_current:next.vitality_current,resource_current:next.resource_current},userId))}return <article className="table-character"><div className="card-heading"><div><p className="eyebrow">Nível {character.level}</p><h2>{character.name}</h2></div>{state?<strong className="vitality-readout">{state.vitality_current}<small> / {state.vitality_max} Vit.</small></strong>:null}</div>{state?<><label className="amount-control">Valor<input aria-label={`Valor para ${character.name}`} type="number" min="1" max={state.vitality_max} value={amount} onChange={e=>setAmount(Math.max(1,Number(e.target.value)||1))}/></label><div className="action-row"><button disabled={!isAdmin} onClick={()=>void alter('damage')}>Aplicar dano</button><button disabled={!isAdmin} onClick={()=>void alter('heal')}>Curar</button></div></>:<p className="muted">Estado não configurado.</p>}<div className="condition-editor"><span>Condições</span><div className="condition-list">{character.character_conditions.map(item=><span key={item.id}>{item.name}{isAdmin?<button aria-label={`Remover ${item.name}`} onClick={()=>void run(()=>removeCondition(item.id))}>×</button>:null}</span>)}</div>{isAdmin?<form onSubmit={e=>{e.preventDefault();void run(()=>addCondition(character.id,condition,userId));setCondition('')}}><input aria-label={`Nova condição para ${character.name}`} maxLength={60} value={condition} onChange={e=>setCondition(e.target.value)} placeholder="Nova condição"/><button>Adicionar</button></form>:null}</div></article>}
