import type { ReactNode } from 'react'
import type { IconName } from '../assets/iconRegistry'
import { ATTRIBUTE_NAMES, type ClassDefinition } from '../game-data/classes'
import { attributeName, classIcon, type CompendiumCategory } from '../game-data/compendium'
import type { EnemyCategory, EnemyStats } from '../game-data/table'
import type { Attributes, Specialty } from '../types/database'
import { CharacterArtwork } from './CharacterArtwork'
import { Icon } from './Icon'
import { RegionArtwork } from './RegionArtwork'

export function CompendiumSearch({value,onChange}:{value:string;onChange:(value:string)=>void}){return <label className="compendium-search"><span><Icon name="compendio" size={18} decorative/>Buscar no Compêndio</span><input type="search" value={value} onChange={event=>onChange(event.target.value)} placeholder="Classe, regra ou termo mecânico…"/></label>}
export function CompendiumFilters({category,onCategory,attribute,onAttribute,enemyLevel,onEnemyLevel}:{category:CompendiumCategory|'all';onCategory:(value:CompendiumCategory|'all')=>void;attribute:keyof Attributes|'all';onAttribute:(value:keyof Attributes|'all')=>void;enemyLevel:number|'all';onEnemyLevel:(value:number|'all')=>void}){return <details className="compendium-filters" open><summary>Filtros</summary><div><label>Categoria<select value={category} onChange={e=>onCategory(e.target.value as CompendiumCategory|'all')}><option value="all">Todas</option>{[['classes','Classes'],['attributes','Atributos'],['specialties','Especialidades'],['conditions','Condições'],['rules','Regras'],['regions','Regiões'],['locations','Locais'],['enemies','Inimigos'],['items','Itens']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Atributo<select value={attribute} onChange={e=>onAttribute(e.target.value as keyof Attributes|'all')}><option value="all">Todos</option>{Object.entries(ATTRIBUTE_NAMES).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Nível de inimigo<select value={enemyLevel} onChange={e=>onEnemyLevel(e.target.value==='all'?'all':Number(e.target.value))}><option value="all">Todos</option>{[1,2,3,4,5].map(level=><option key={level} value={level}>Nível {level}</option>)}</select></label></div></details>}
export function CompendiumSection({id,title,count,children}:{id:CompendiumCategory;title:string;count:number;children:ReactNode}){return <section className="compendium-section" id={`compendio-${id}`} aria-labelledby={`title-${id}`}><header><p>{String(count).padStart(2,'0')} referências</p><h2 id={`title-${id}`}>{title}</h2></header>{children}</section>}
export function CompendiumCard({icon,title,kicker,children,onOpen}:{icon:IconName;title:string;kicker?:string;children:ReactNode;onOpen?:()=>void}){const body=<><span className="compendium-card__icon"><Icon name={icon} size={24} decorative/></span><div>{kicker?<p>{kicker}</p>:null}<h3>{title}</h3>{children}</div></>;return onOpen?<button type="button" className="compendium-card" onClick={onOpen}>{body}<span className="compendium-card__action">Consultar →</span></button>:<article className="compendium-card">{body}</article>}
export function ClassCompendiumCard({definition,onOpen}:{definition:ClassDefinition;onOpen:()=>void}){return <button className="class-compendium-card" type="button" onClick={onOpen} data-class={definition.key}><CharacterArtwork classKey={definition.key}/><span className="class-compendium-card__veil"/><div><p><Icon name={classIcon(definition.key)} size={20} decorative/>{definition.role}</p><h3>{definition.name}</h3><dl><div><dt>Atributo</dt><dd>{ATTRIBUTE_NAMES[definition.primary]}</dd></div><div><dt>Recurso</dt><dd>{definition.resource}</dd></div><div><dt>Vitalidade</dt><dd>{definition.baseVitality}</dd></div></dl><span>Ver referência completa →</span></div></button>}
export function RegionCompendiumCard({region,onOpen}:{region:{key:string;name:string;aliases:readonly string[]};onOpen:()=>void}){return <button className="region-compendium-card" type="button" onClick={onOpen}><RegionArtwork region={region.key} alt={region.name}/><span/><div><p>Região registrada</p><h3>{region.name}</h3>{region.aliases.length>1?<small>Também registrada como {region.aliases.slice(1).join(', ')}</small>:null}</div></button>}
export function RuleCard({name,icon,text,onOpen}:{name:string;icon:IconName;text:string;onOpen:()=>void}){return <CompendiumCard icon={icon} title={name} kicker="Regra do sistema" onOpen={onOpen}><p>{text}</p></CompendiumCard>}
export function ConditionReference({name,icon,onOpen}:{name:string;icon:IconName;onOpen:()=>void}){return <CompendiumCard icon={icon} title={name} kicker="Condição" onOpen={onOpen}><p>Duração: rodadas, cena ou indefinida. Efeito e remoção não documentados.</p></CompendiumCard>}
export function EnemyReferenceCard({level,category,stats,onOpen}:{level:number;category:EnemyCategory;stats:EnemyStats;onOpen:()=>void}){return <CompendiumCard icon={category==='chefe'?'chefe':'monstro'} title={`Nível ${level} · ${category}`} kicker="Template mecânico" onOpen={onOpen}><dl className="enemy-reference-stats"><div><dt>VIT</dt><dd>{stats.vitalityMax}</dd></div><div><dt>DEF</dt><dd>{stats.defense}</dd></div><div><dt>ATQ</dt><dd>+{stats.attackBonus}</dd></div><div><dt>Dano</dt><dd>{stats.damage}</dd></div><div><dt>DT efeito</dt><dd>{stats.effectDifficulty}</dd></div></dl></CompendiumCard>}
export function CompendiumEmptyState({title,icons}:{title:string;icons:IconName[]}){return <div className="compendium-empty"><div>{icons.map(icon=><Icon key={icon} name={icon} size={22} decorative/>)}</div><h3>{title}</h3><p>Conteúdo ainda não cadastrado.</p></div>}
export function CompendiumDetail({title,icon,children,onClose}:{title:string;icon:IconName;children:ReactNode;onClose:()=>void}){return <div className="compendium-detail-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="compendium-detail" role="dialog" aria-modal="true" aria-labelledby="compendium-detail-title"><header><Icon name={icon} size={28} decorative/><h2 id="compendium-detail-title">{title}</h2><button type="button" onClick={onClose} aria-label="Fechar detalhe">×</button></header><div>{children}</div></section></div>}
export function SpecialtyReference({name,attribute,description,onOpen}:{name:Specialty;attribute:keyof Attributes|undefined;description:string;onOpen:()=>void}){return <CompendiumCard icon="habilidades" title={name} kicker={attributeName(attribute)} onOpen={onOpen}><p>{description}</p><small>Treinada e relacionada: +1 no teste.</small></CompendiumCard>}
