import { useCallback,useEffect,useMemo,useState } from 'react'
import { archiveEvent,getEventPrefs,loadEventsPage,resetHiddenBefore,setHiddenBefore,subscribeToEvents,type EventFilter } from '../data/events'
import { supabase } from '../lib/supabase'
import type { CampaignEvent } from '../types/database'
import { MechanicalButton,SectionTitle } from './RelicarioUI'
type Scope='session'|'all';type Kind='all'|'pending'|'completed'|'tests'|'pools'|'combat'
const COMBAT=['combat_started','combat_ended','enemy_created','enemy_changed','character_fallen','character_stable','turn_advanced','turn_selected','initiative_reordered','enemy_attack','enemy_attack_miss','condition_added']
const attr:Record<string,string>={strength:'Força',agility:'Agilidade',intellect:'Intelecto',presence:'Presença',instinct:'Instinto'}
const text=(p:Record<string,unknown>,k:string)=>typeof p[k]==='string'?p[k] as string:null
const number=(p:Record<string,unknown>,k:string)=>typeof p[k]==='number'?p[k] as number:null
type Entry={key:string;request?:CampaignEvent;result?:CampaignEvent;event:CampaignEvent}
function group(events:CampaignEvent[]):Entry[]{const map=new Map<string,Entry>();for(const event of events){const id=text(event.payload??{},'roll_request_id');if(!id){map.set(event.id,{key:event.id,event});continue}const found=map.get(id)??{key:id,event};if(event.event_type==='roll_requested')found.request=event;else if(event.event_type==='dice_roll')found.result=event;if(event.sequence>found.event.sequence)found.event=event;map.set(id,found)}return [...map.values()].sort((a,b)=>b.event.sequence-a.event.sequence)}
function view(entry:Entry){const event=entry.result??entry.request??entry.event,p=event.payload??{},kind=text(p,'request_kind')??'character_test',name=text(p,'character_name')??(kind==='dice_pool'?'Dados livres':event.summary),facets=[text(p,'attribute')?attr[text(p,'attribute')!]:null,text(p,'specialty')].filter(Boolean).join(' + '),label=text(p,'test_label')??(facets||(kind==='character_test'?'Teste simples':'Dados livres')),difficulty=number(p,'difficulty'),total=number(p,'total'),outcome=text(p,'outcome'),results=Array.isArray(p.results)?p.results.join(' + '):null;return{event,p,kind,name,title:`${label}${difficulty!=null?` · Dificuldade ${difficulty}`:''}`,reason:text(p,'reason'),result:entry.result?(kind==='dice_pool'?`Resultados ${results??'—'} · Total ${total??'—'}`:`Resultado ${total??'—'}${outcome?` · ${outcome.includes('success')?'Sucesso':'Falha'}`:''}`):'Aguardando'}}
export function HistoryPanel({campaignId,sessionId,userId,isAdmin}:{campaignId:string;sessionId:string|null;userId:string;isAdmin:boolean}){
 const[events,setEvents]=useState<CampaignEvent[]>([]),[scope,setScope]=useState<Scope>('session'),[kind,setKind]=useState<Kind>('all'),[archived,setArchived]=useState(false),[hidden,setHidden]=useState(0),[more,setMore]=useState(true),[loading,setLoading]=useState(false)
 const filter:EventFilter=useMemo(()=>({sessionId:scope==='session'?sessionId:undefined,includeTests:true,includeArchived:archived}),[scope,sessionId,archived])
 const load=useCallback(async()=>{const page=await loadEventsPage(campaignId,filter);setEvents(page);setMore(page.length>0)},[campaignId,filter])
 useEffect(()=>{void load()},[load]);useEffect(()=>{void getEventPrefs(campaignId,userId).then(setHidden)},[campaignId,userId]);useEffect(()=>{const channel=subscribeToEvents(campaignId,event=>setEvents(current=>current.some(x=>x.id===event.id)?current:[event,...current]));return()=>{void supabase.removeChannel(channel)}},[campaignId])
 let entries=group(events.filter(e=>e.sequence>hidden));entries=entries.filter(entry=>{const v=view(entry);if(kind==='all')return true;if(kind==='pending')return Boolean(entry.request&&!entry.result);if(kind==='completed')return Boolean(entry.result);if(kind==='tests')return v.kind==='character_test'&&(entry.request||entry.result);if(kind==='pools')return v.kind==='dice_pool';return COMBAT.includes(entry.event.event_type)})
 async function loadMore(){if(!events.length)return;setLoading(true);try{const page=await loadEventsPage(campaignId,filter,events.at(-1)?.sequence);setEvents(current=>[...current,...page]);setMore(page.length>0)}finally{setLoading(false)}}
 return <section className="history-panel" aria-label="Histórico da Mesa"><SectionTitle icon="diario" title="Histórico" description="Solicitações e resultados reunidos em um único registro."/><details className="history-filters-wrap"><summary>Filtros e arquivamento</summary><div className="history-filters"><select aria-label="Escopo" value={scope} onChange={e=>setScope(e.target.value as Scope)}><option value="session">Sessão atual</option><option value="all">Todas as sessões</option></select><div className="history-filter-chips" role="group" aria-label="Tipo">{([['all','Todos'],['pending','Pendentes'],['completed','Concluídos'],['tests','Testes'],['pools','Dados livres'],['combat','Combate']] as const).map(([value,label])=><button type="button" aria-pressed={kind===value} key={value} onClick={()=>setKind(value)}>{label}</button>)}</div>{isAdmin?<label><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Mostrar arquivados</label>:null}{hidden?<MechanicalButton onClick={()=>void resetHiddenBefore(campaignId,userId).then(()=>setHidden(0))}>Mostrar tudo novamente</MechanicalButton>:<MechanicalButton onClick={()=>{const latest=events[0]?.sequence??0;void setHiddenBefore(campaignId,userId,latest).then(()=>setHidden(latest))}}>Limpar visualização</MechanicalButton>}</div></details>{entries.length?<ol className="history-list">{entries.map(entry=>{const v=view(entry);return <li key={entry.key} className="history-item"><span className="history-item__icon" aria-hidden="true">{entry.result?'◆':entry.request?'◷':'•'}</span><div className="history-item__body"><strong className="history-item__character">{v.name}</strong><p className="history-item__headline">{v.title}</p>{v.reason?<p className="history-item__detail">{v.reason}</p>:null}<p className="history-item__result">{v.result}</p><time dateTime={v.event.created_at}>{new Date(v.event.created_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</time></div><details className="history-item__menu"><summary aria-label={`Ações para ${v.name}`}>•••</summary><div>{isAdmin&&!v.event.is_archived?<button type="button" onClick={()=>void archiveEvent(v.event.id).then(load)}>Arquivar</button>:null}<details className="history-item__details"><summary>Ver detalhes</summary><dl>{v.reason?<div><dt>Motivo</dt><dd>{v.reason}</dd></div>:null}<div><dt>Dados</dt><dd>{v.title}</dd></div><div><dt>Modificador</dt><dd>{number(v.p,'modifier')??0}</dd></div><div><dt>Resultado</dt><dd>{v.result}</dd></div><div><dt>Data</dt><dd>{new Date(v.event.created_at).toLocaleString('pt-BR')}</dd></div></dl></details></div></details></li>})}</ol>:<p className="compact-empty">Nenhum evento neste filtro.</p>}{more&&events.length>=30?<MechanicalButton disabled={loading} onClick={()=>void loadMore()}>{loading?'Carregando…':'Carregar mais'}</MechanicalButton>:null}</section>
}
