import { useEffect, useRef, useState } from 'react'
import { Icon } from '../Icon'
import { CharacterPortrait } from '../CharacterPortrait'
import { RegionArtwork } from '../RegionArtwork'
import { ConditionBadge, ResourceBar } from '../CharacterCard'
import { getClassDefinition, ATTRIBUTE_NAMES, SPECIALTIES } from '../../game-data/classes'
import { advanceTurn, attributeModifier, DIE_SIDES, enemyStats, normalizeConditionDuration, rollDice, rollDicePool, type ConditionDuration, type DicePool, type DicePoolResult, type DieSides, type EnemyCategory, type EnemyLevel, type MechanicalCondition, type RollResult, type Zone } from '../../game-data/table'
import type { Character, Specialty } from '../../types/database'

export const CONDITIONS=['Ferido','Exausto','Amedrontado','Envenenado','Imobilizado','Desorientado','Corrompido'] as const
export type TableCondition=typeof CONDITIONS[number]
export function DiceResult({result}:{result:RollResult|null}){if(!result)return null;return <output className={`dice-result ${result.critical?'is-critical':''} ${result.complication?'is-complication':''}`} aria-live="polite"><span className="dice-result__label">Resultado</span><strong>{result.total}</strong><span className="dice-result__calculation"><b>{result.rolls.join(' + ')}</b>{result.modifier?` + bônus ${result.modifier}`:''} = {result.total}</span>{result.critical?<em>Crítico: 20 natural</em>:result.complication?<em>Complicação: 1 natural</em>:result.naturalD20?<em>Natural {result.naturalD20}</em>:null}</output>}

function DiceTray({result,pool,rolling,rollKey}:{result:DicePoolResult|null;pool:DicePool;rolling:boolean;rollKey:number}){
  const rolledDice=result?.entries.flatMap(entry=>entry.rolls.map(value=>({sides:entry.sides,value})))??[]
  const selectedDice=DIE_SIDES.flatMap(sides=>Array.from({length:pool[sides]??0},()=>({sides,value:null})))
  const visibleDice=(result?rolledDice:selectedDice).slice(0,12)
  const hiddenCount=(result?rolledDice:selectedDice).length-visibleDice.length
  return <div className={`dice-tray ${rolling?'is-rolling':''}`} aria-busy={rolling}>
    <div className="dice-tray__heading"><span>Bandeja de rolagem</span>{result?<strong>Total {result.total}</strong>:<strong>{selectedDice.length} dado(s)</strong>}</div>
    <div className="dice-tray__surface" key={rollKey} aria-hidden="true">
      {visibleDice.map((die,index)=><span className={`die-token ${die.value===null?'die-token--idle ':''}die-token--d${die.sides}`} key={`${rollKey}-${die.sides}-${index}`}><small>d{die.sides}</small><b>{die.value??'?'}</b></span>)}
      {hiddenCount>0?<span className="dice-tray__more">+{hiddenCount}</span>:null}
    </div>
    <output className="dice-tray__result" aria-live="polite">
      {result?<><span>{result.quantity} dado(s) lançados</span><em>Total {result.total}</em></>:<span>Monte o conjunto e faça sua rolagem.</span>}
    </output>
    {result?<ul className="dice-roll-breakdown">{result.entries.map(entry=><li key={entry.sides}><span>d{entry.sides}</span><b>{entry.rolls.join(' · ')}</b><strong>{entry.rolls.reduce((sum,value)=>sum+value,0)}</strong></li>)}</ul>:null}
  </div>
}

export function DiceRoller({onRoll}:{onRoll?:(result:DicePoolResult)=>void}){
  const[pool,setPool]=useState<DicePool>({20:1}),[reason,setReason]=useState(''),[result,setResult]=useState<DicePoolResult|null>(null),[rolling,setRolling]=useState(false),[rollKey,setRollKey]=useState(0)
  const rollTimeout=useRef<number|null>(null)
  useEffect(()=>()=>{if(rollTimeout.current!==null)window.clearTimeout(rollTimeout.current)},[])
  const quantity=DIE_SIDES.reduce((sum,sides)=>sum+(pool[sides]??0),0)
  function changeDie(sides:DieSides,delta:number){setPool(current=>({...current,[sides]:Math.max(0,Math.min(10,(current[sides]??0)+delta))}));setResult(null)}
  function roll(){
    if(!quantity)return
    const value=rollDicePool(pool)
    if(rollTimeout.current!==null)window.clearTimeout(rollTimeout.current)
    setResult(value);setRolling(true);setRollKey(key=>key+1);onRoll?.(value)
    rollTimeout.current=window.setTimeout(()=>setRolling(false),720)
  }
  return <section className="dice-roller" aria-labelledby="dice-title">
    <div className="table-section-heading"><Icon name="teste-d20" decorative/><div><h2 id="dice-title">Rolador de dados</h2><p>Role na bandeja. O resultado continua calculado no navegador.</p></div></div>
    <DiceTray result={result} pool={pool} rolling={rolling} rollKey={rollKey}/>
    <div className="dice-picker" aria-label="Escolher dados">{DIE_SIDES.map(sides=><div className={`dice-choice ${pool[sides]?'is-selected':''}`} key={sides}><button type="button" className={`dice-choice__add die-token--d${sides}`} aria-label={`Adicionar d${sides}`} onClick={()=>changeDie(sides,1)}><span>d{sides}</span>{pool[sides]?<b>{pool[sides]}</b>:null}</button><button type="button" className="dice-choice__remove" aria-label={`Remover d${sides}`} disabled={!pool[sides]} onClick={()=>changeDie(sides,-1)}>−</button></div>)}</div>
    <div className="dice-roll-options"><label>Motivo opcional<input name="dice-reason" maxLength={80} placeholder="Ex.: dano da armadilha" value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="button" onClick={()=>{setPool({});setResult(null)}} disabled={!quantity}>Limpar</button></div>
    <button className={`primary-button dice-button ${rolling?'is-rolling':''}`} type="button" onClick={roll} disabled={rolling||!quantity}><Icon name="teste-d20" size={19} decorative/>{rolling?'Rolando...':`Rolar ${quantity} dado${quantity===1?'':'s'}${reason?` · ${reason}`:''}`}</button>
  </section>
}
export function QuickRoll({characters,onRoll}:{characters:Character[];onRoll?:(result:RollResult)=>void}){const[id,setId]=useState(characters[0]?.id??''),[attribute,setAttribute]=useState<keyof Character['attributes']>('strength'),[specialty,setSpecialty]=useState<Specialty|''>(''),[difficulty,setDifficulty]=useState(''),[result,setResult]=useState<RollResult|null>(null);const character=characters.find(c=>c.id===id);const available=character?.character_specialties.map(s=>s.name)??[];const bonus=character?attributeModifier(character.attributes,attribute,specialty||undefined,available):0;function run(){if(!character)return;const value=rollDice(20,1,bonus);setResult(value);onRoll?.(value)}return <section className="quick-roll"><div className="quick-roll__heading"><Icon name="teste-d20" size={22} decorative/><div><h2>Teste de atributo</h2><p>1d20 + atributo{specialty?' + especialidade':''}</p></div><strong>+{bonus}</strong></div><div className="quick-roll__grid"><label>Personagem<select name="quick-roll-character" value={id} onChange={e=>setId(e.target.value)}>{characters.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Atributo<select name="quick-roll-attribute" value={attribute} onChange={e=>setAttribute(e.target.value as keyof Character['attributes'])}>{Object.entries(ATTRIBUTE_NAMES).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><label>Especialidade<select name="quick-roll-specialty" value={specialty} onChange={e=>setSpecialty(e.target.value as Specialty|'')}><option value="">Nenhuma</option>{SPECIALTIES.filter(s=>available.includes(s)).map(s=><option key={s}>{s}</option>)}</select></label><label>Dificuldade <span>opcional</span><input name="quick-roll-difficulty" type="number" min="1" placeholder="—" value={difficulty} onChange={e=>setDifficulty(e.target.value)}/></label></div><button className="quick-roll__button" type="button" onClick={run} disabled={!character}><Icon name="teste-d20" size={18} decorative/>Rolar teste</button><DiceResult result={result}/>{result&&difficulty?<p className={`roll-verdict ${result.total>=Number(difficulty)?'is-success':'is-failure'}`}>{result.total>=Number(difficulty)?'Sucesso':'Falha'} contra dificuldade {difficulty}.</p>:null}</section>}

type ResourceAction='damage'|'heal'|'spend'|'recover'
export function ResourceControl({disabled,onDamage,onHeal,onResource}:{disabled:boolean;onDamage:(n:number)=>void;onHeal:(n:number)=>void;onResource:(n:number)=>void}){const[value,setValue]=useState(1),[pending,setPending]=useState<ResourceAction|null>(null);const labels:Record<ResourceAction,string>={damage:'Aplicar dano',heal:'Aplicar cura',spend:'Gastar recurso',recover:'Recuperar recurso'};function run(action:ResourceAction){if(action==='damage')onDamage(value);else if(action==='heal')onHeal(value);else onResource(action==='spend'?-value:value);setPending(null)}function request(action:ResourceAction){if(action==='damage'||action==='spend')setPending(action);else run(action)}return <section className="resource-control" aria-label="Ajustes rápidos"><div className="resource-control__heading"><span>Ajustes rápidos</span><label>Valor<input type="number" min="1" inputMode="numeric" value={value} onChange={e=>{setValue(Math.max(1,Number(e.target.value)||1));setPending(null)}}/></label></div><div className="resource-actions" aria-label="Ajustar estado do personagem"><button type="button" title="Aplicar dano" aria-label="Dano" className="resource-action resource-action--damage" disabled={disabled} onClick={()=>request('damage')}><Icon name="dano" size={22} decorative/></button><button type="button" title="Aplicar cura" aria-label="Cura" className="resource-action resource-action--heal" disabled={disabled} onClick={()=>request('heal')}><Icon name="cura" size={22} decorative/></button><button type="button" title="Gastar recurso" aria-label="Gastar recurso" className="resource-action resource-action--spend" disabled={disabled} onClick={()=>request('spend')}><Icon name="recurso-de-classe" size={22} decorative/><span className="resource-action__sign" aria-hidden="true">−</span></button><button type="button" title="Recuperar recurso" aria-label="Recuperar recurso" className="resource-action resource-action--recover" disabled={disabled} onClick={()=>request('recover')}><Icon name="recurso-de-classe" size={22} decorative/><span className="resource-action__sign" aria-hidden="true">+</span></button></div>{pending?<div className="resource-confirm" role="group" aria-label={`Confirmar ${labels[pending].toLowerCase()}`}><span>{labels[pending]}: <strong>{value}</strong>?</span><button type="button" onClick={()=>setPending(null)}>Cancelar</button><button type="button" className="resource-confirm__submit" onClick={()=>run(pending)}>Confirmar</button></div>:null}</section>}

function PlayerScene({character,region}:{character:Character;region:string}){
  return <div className="player-combat-scene"><RegionArtwork region={region} alt={`Cenário de ${region}`} loading="eager"/><div className="player-combat-scene__shade" aria-hidden="true"/><CharacterPortrait compact classKey={character.class_key} name={character.name} avatar={character.avatar}/><span className="player-combat-scene__region"><Icon name="mapa" size={15} decorative/>{region}</span></div>
}
export function ConditionEditor({disabled,conditions,combatConditions=[],onAdd,onRemove}:{disabled:boolean;conditions:Character['character_conditions'];combatConditions?:MechanicalCondition[];onAdd:(name:TableCondition,duration:ConditionDuration)=>void;onRemove:(id:string,name:string)=>void}){const[name,setName]=useState<TableCondition>('Ferido'),[duration,setDuration]=useState<ConditionDuration['kind']>('scene'),[rounds,setRounds]=useState(1),hasConditions=conditions.length>0||combatConditions.length>0;return <section className="condition-editor"><div className="condition-editor__heading"><span>Condições</span>{!hasConditions?<small>Nenhuma ativa</small>:null}</div>{hasConditions?<ul className="condition-list">{conditions.map(c=><ConditionBadge key={c.id} name={c.name}/>)}{combatConditions.map((c,index)=><li key={`${c.name}-${index}`}>{c.name} · {c.duration.kind==='rounds'?`${c.duration.rounds} rodada(s)`:c.duration.kind==='scene'?'cena':'indefinida'}</li>)}</ul>:null}{!disabled?<div className="condition-add"><select aria-label="Condição" value={name} onChange={e=>setName(e.target.value as TableCondition)}>{CONDITIONS.map(c=><option key={c}>{c}</option>)}</select><select aria-label="Duração" value={duration} onChange={e=>setDuration(e.target.value as ConditionDuration['kind'])}><option value="rounds">Rodadas</option><option value="scene">Cena</option><option value="indefinite">Indefinida</option></select>{duration==='rounds'?<input aria-label="Quantidade de rodadas" type="number" min="1" value={rounds} onChange={e=>setRounds(Math.max(1,Number(e.target.value)||1))}/>:null}<button type="button" onClick={()=>onAdd(name,normalizeConditionDuration(duration,rounds))}>Adicionar</button></div>:null}{!disabled&&conditions.length?<div className="condition-remove">{conditions.map(c=><button type="button" key={c.id} onClick={()=>onRemove(c.id,c.name)}>Remover {c.name}</button>)}</div>:null}</section>}
export function PlayerCombatCard({character,playerName,isAdmin,combatConditions,fallen,stable,currentRegion,onDamage,onHeal,onResource,onAddCondition,onRemoveCondition,onFallen,onStabilize}:{character:Character;playerName?:string;isAdmin:boolean;combatConditions?:MechanicalCondition[];fallen?:boolean;stable?:boolean;currentRegion:string;onDamage:(n:number)=>void;onHeal:(n:number)=>void;onResource:(n:number)=>void;onAddCondition:(n:TableCondition,duration:ConditionDuration)=>void;onRemoveCondition:(id:string,name:string)=>void;onFallen:()=>void;onStabilize:()=>void}){const state=character.character_states,role=getClassDefinition(character.class_key),isFallen=fallen||state?.vitality_current===0||character.character_conditions.some(c=>c.name==='Caído');return <article className={`player-combat-card ${isFallen?'is-fallen':''}`}><aside className="player-combat-card__aside"><PlayerScene character={character} region={currentRegion}/>{isAdmin&&state?<div className="fall-actions" aria-label="Estado de queda"><button type="button" onClick={onFallen}>Marcar Caído</button><button type="button" disabled={!isFallen||stable} onClick={onStabilize}>Estabilizar</button></div>:null}</aside><div className="player-combat-card__body"><div className="card-heading"><div><span>Nível {character.level}{playerName?` · ${playerName}`:''}</span><h2>{character.name}</h2><p>{role.name}</p></div><strong><Icon name="defesa" size={18} decorative/> {character.defense}</strong></div>{isFallen?<p className="fallen-state">{stable?'Caído e estável':'Caído'}</p>:null}{state?<><div className="player-vitals"><ResourceBar icon="vitalidade" label="Vitalidade" value={state.vitality_current} max={state.vitality_max} tone="vitality"/><ResourceBar icon="recurso-de-classe" label={role.resource} value={state.resource_current} max={state.resource_max} tone="resource"/></div><div className="player-controls"><ResourceControl disabled={!isAdmin} onDamage={onDamage} onHeal={onHeal} onResource={onResource}/></div></>:<p>Estado mecânico indisponível.</p>}<ConditionEditor disabled={!isAdmin} conditions={character.character_conditions} combatConditions={combatConditions} onAdd={onAddCondition} onRemove={onRemoveCondition}/></div></article>}

export type Enemy={id:string;name:string;level:EnemyLevel;category:EnemyCategory;archetype:string;vitality:number;vitalityMax:number;defense:number;attackBonus:number;damage:string;effectDifficulty:number;zone:Zone;status:'ativo'|'derrotado'|'fugiu'|'aliado';description?:string;initiative:number;conditions?:MechanicalCondition[]}
export function EnemyCreator({onCreate}:{onCreate:(enemy:Enemy)=>void}){const[name,setName]=useState(''),[level,setLevel]=useState<EnemyLevel>(1),[category,setCategory]=useState<EnemyCategory>('comum'),[archetype,setArchetype]=useState('brutamontes');function create(){if(!name.trim())return;const stats=enemyStats(level,category);onCreate({id:crypto.randomUUID(),name:name.trim(),level,category,archetype,vitality:stats.vitalityMax,...stats,zone:'perto',status:'ativo',initiative:0});setName('')}return <section className="enemy-creator"><h2>Adicionar inimigo</h2><div className="dice-grid"><label>Nome<input value={name} onChange={e=>setName(e.target.value)} maxLength={60}/></label><label>Nível<select value={level} onChange={e=>setLevel(Number(e.target.value) as EnemyLevel)}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value as EnemyCategory)}>{['lacaio','comum','elite','chefe'].map(c=><option key={c}>{c}</option>)}</select></label><label>Arquétipo<select value={archetype} onChange={e=>setArchetype(e.target.value)}>{['brutamontes','guardião','perseguidor','atirador','controlador','conjurador','suporte'].map(a=><option key={a}>{a}</option>)}</select></label></div><button disabled={!name.trim()} onClick={create}>Adicionar ao combate</button></section>}
export function EnemyCard({enemy,isAdmin,onChange}:{enemy:Enemy;isAdmin:boolean;onChange:(e:Enemy)=>void}){return <article className="enemy-card"><div><Icon name={enemy.category==='chefe'?'chefe':'monstro'} decorative/><h3>{enemy.name}</h3><span>Nível {enemy.level} · {enemy.category} · {enemy.archetype}</span></div><dl><div><dt>Vitalidade</dt><dd>{enemy.vitality}/{enemy.vitalityMax}</dd></div><div><dt>Defesa</dt><dd>{enemy.defense}</dd></div><div><dt>Ataque</dt><dd>+{enemy.attackBonus}</dd></div><div><dt>Dano</dt><dd>{enemy.damage}</dd></div><div><dt>Dificuldade</dt><dd>{enemy.effectDifficulty}</dd></div></dl>{isAdmin?<div className="enemy-actions"><button onClick={()=>onChange({...enemy,vitality:Math.max(0,enemy.vitality-1),status:enemy.vitality<=1?'derrotado':enemy.status})}>Sofrer 1 dano</button><button onClick={()=>onChange({...enemy,status:'fugiu'})}>Fugir</button><select aria-label={`Zona de ${enemy.name}`} value={enemy.zone} onChange={e=>onChange({...enemy,zone:e.target.value as Zone})}>{['corpo a corpo','perto','distante','fora de alcance'].map(z=><option key={z}>{z}</option>)}</select></div>:null}</article>}
export function InitiativeTracker({participants,turn,isAdmin,onTurn,onInitiative,onReorder}:{participants:{id:string;name:string;initiative:number}[];turn:number;isAdmin:boolean;onTurn:(turn:number)=>void;onInitiative:(id:string,value:number)=>void;onReorder:(from:number,to:number)=>void}){return <ol className="initiative-list">{participants.map((p,index)=><li key={p.id} className={index===turn?'is-current':''}><span>{index+1}. {p.name}</span>{isAdmin?<input aria-label={`Iniciativa de ${p.name}`} type="number" value={p.initiative} onChange={e=>onInitiative(p.id,Number(e.target.value)||0)}/>:<strong>{p.initiative}</strong>}{isAdmin?<><button onClick={()=>onTurn(index)}>Definir turno</button><button disabled={index===0} onClick={()=>onReorder(index,index-1)}>Subir</button><button disabled={index===participants.length-1} onClick={()=>onReorder(index,index+1)}>Descer</button></>:null}</li>)}</ol>}
export function EnemyAttackPanel({enemies,characters,disabled,onAttack}:{enemies:Enemy[];characters:Character[];disabled:boolean;onAttack:(enemy:Enemy,target:Character)=>void}){const[enemyId,setEnemyId]=useState(''),[targetId,setTargetId]=useState('');const enemy=enemies.find(item=>item.id===(enemyId||enemies[0]?.id)),target=characters.find(item=>item.id===(targetId||characters[0]?.id));return <section><h2>Ataque do inimigo</h2><label>Inimigo<select value={enemy?.id??''} onChange={e=>setEnemyId(e.target.value)}>{enemies.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Alvo<select value={target?.id??''} onChange={e=>setTargetId(e.target.value)}>{characters.map(item=><option key={item.id} value={item.id}>{item.name} · Defesa {item.defense}</option>)}</select></label><button disabled={disabled||!enemy||!target} onClick={()=>enemy&&target&&onAttack(enemy,target)}>Rolar ataque</button></section>}
export function CombatControls({round,turn,count,onAdvance,onEnd}:{round:number;turn:number;count:number;onAdvance:(next:{round:number;turn:number})=>void;onEnd:()=>void}){return <div className="combat-controls"><strong>Rodada {round} · turno {count?turn+1:0}</strong><button onClick={()=>onAdvance(advanceTurn(turn,round,count))}>Avançar turno</button><button className="danger-button" onClick={onEnd}>Encerrar combate</button></div>}
export function CombatEmptyState({onStart,disabled}:{onStart:()=>void;disabled:boolean}){return <section className="combat-empty"><Icon name="monstro" size={38} decorative/><h2>Nenhum combate ativo</h2><p>Inicie somente quando o GPT Mestre indicar uma situação mecânica.</p><button disabled={disabled} onClick={onStart}>Iniciar combate</button></section>}
export function ActionToast({message}:{message:string|null}){return message?<div className="action-toast" role="status">{message}</div>:null}
