import { publicAssetUrl } from './publicAssetUrl'

export type IconCategory = 'classes'|'attributes'|'settlements'|'locations'|'exploration'|'threats'|'mechanics'|'conditions'|'character-sheet'|'navigation'|'identity'
type IconAsset = { path: string; label: string; category: IconCategory }
const icon = (category: IconCategory, name: string, label: string): IconAsset => ({ path: publicAssetUrl(`icons/${category}/${name}.svg`), label, category })

const ICONS = {
  guerreiro: icon('classes','guerreiro','Guerreiro'), arcanista: icon('classes','arcanista','Arcanista'), 'lamina-sombria': icon('classes','lamina-sombria','Lâmina Sombria'), necromante: icon('classes','necromante','Necromante'), bardo: icon('classes','bardo','Bardo'), druida: icon('classes','druida','Druida'),
  forca: icon('attributes','forca','Força'), agilidade: icon('attributes','agilidade','Agilidade'), intelecto: icon('attributes','intelecto','Intelecto'), presenca: icon('attributes','presenca','Presença'), instinto: icon('attributes','instinto','Instinto'),
  metropole: icon('settlements','metropole','Metrópole'), cidade: icon('settlements','cidade','Cidade'), vila: icon('settlements','vila','Vila'), fortaleza: icon('settlements','fortaleza','Fortaleza'), castelo: icon('settlements','castelo','Castelo'), acampamento: icon('settlements','acampamento','Acampamento'), mosteiro: icon('settlements','mosteiro','Mosteiro'), observatorio: icon('settlements','observatorio','Observatório'),
  ruinas: icon('locations','ruinas','Ruínas'), caverna: icon('locations','caverna','Caverna'), mina: icon('locations','mina','Mina'), porto: icon('locations','porto','Porto'), 'ponte-passagem': icon('locations','ponte-passagem','Ponte ou passagem'), estrada: icon('locations','estrada','Estrada'),
  'local-revelado': icon('exploration','local-revelado','Local revelado'), 'local-oculto': icon('exploration','local-oculto','Local oculto'), missao: icon('exploration','missao','Missão'), rumor: icon('exploration','rumor','Rumor'),
  monstro: icon('threats','monstro','Monstro'), chefe: icon('threats','chefe','Chefe'), covil: icon('threats','covil','Covil'), corrupcao: icon('threats','corrupcao','Corrupção'), armadilha: icon('threats','armadilha','Armadilha'), 'rota-bloqueada': icon('threats','rota-bloqueada','Rota bloqueada'),
  'teste-d20': icon('mechanics','teste-d20','Teste de d20'), vitalidade: icon('mechanics','vitalidade','Vitalidade'), 'recurso-de-classe': icon('mechanics','recurso-de-classe','Recurso de classe'), defesa: icon('mechanics','defesa','Defesa'), dano: icon('mechanics','dano','Dano'), cura: icon('mechanics','cura','Cura'),
  masculino: icon('identity','masculino','Masculino'), feminino: icon('identity','feminino','Feminino'),
  'condicao-generica': icon('conditions','condicao-generica','Condição'), ferido: icon('conditions','ferido','Ferido'), exausto: icon('conditions','exausto','Exausto'), amedrontado: icon('conditions','amedrontado','Amedrontado'), envenenado: icon('conditions','envenenado','Envenenado'), imobilizado: icon('conditions','imobilizado','Imobilizado'), desorientado: icon('conditions','desorientado','Desorientado'),
  inventario: icon('character-sheet','inventario','Inventário'), equipamento: icon('character-sheet','equipamento','Equipamento'), habilidades: icon('character-sheet','habilidades','Habilidades'), nivel: icon('character-sheet','nivel','Nível'), ouro: icon('character-sheet','ouro','Ouro'), diario: icon('character-sheet','diario','Diário'), capacete: icon('character-sheet','capacete','Capacete'), armadura: icon('character-sheet','armadura','Armadura'), luvas: icon('character-sheet','luvas','Luvas'), botas: icon('character-sheet','botas','Botas'), anel: icon('character-sheet','anel','Anel'), amuleto: icon('character-sheet','amuleto','Amuleto'),
  campanhas: icon('navigation','campanhas','Campanhas'), personagens: icon('navigation','personagens','Personagens'), mapa: icon('navigation','mapa','Mapa'), mesa: icon('navigation','mesa','Mesa'), compendio: icon('navigation','compendio','Compêndio'), configuracoes: icon('navigation','configuracoes','Configurações'), 'nova-campanha': icon('navigation','nova-campanha','Nova campanha'), 'exportar-para-gpt': icon('navigation','exportar-para-gpt','Exportar para GPT'), 'missao-de-campanha': icon('navigation','missao-de-campanha','Missão de campanha'), npc: icon('navigation','npc','NPC'), mestre: icon('navigation','mestre','Mestre'), 'assento-vazio': icon('navigation','assento-vazio','Assento vazio'),
} as const satisfies Record<string, IconAsset>

export const iconRegistry: Readonly<typeof ICONS> = ICONS
export type IconName = keyof typeof ICONS
export const iconNames = Object.keys(ICONS) as IconName[]
